# -*- coding: utf-8 -*-
"""Abeera_BioAI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fYLfo68eMkm5TU0t77-3OLqMboFKMfki

## 🧬 **Abeera BioAI**

Abeera BioAI 🧬 is a lightweight, **AI-powered bioinformatics assistant developed by Abeera Iftikhar**.
It is designed to support students and researchers in understanding and exploring core concepts of bioinformatics, including genomics, protein analysis, sequence interpretation, and computational biology tasks.

This project integrates modern large language models via the Groq API with a simple and interactive user interface built using Gradio. It enables real-time conversational responses for biological and computational queries without requiring complex setup or coding knowledge from the user.

## 🚀 Key Features
AI-powered conversational bioinformatics assistant
Real-time responses using LLaMA-based models via Groq
Interactive web interface using Gradio
Lightweight and easy to run in Google Colab
Suitable for beginners in bioinformatics and AI

## 🧠 Purpose
The goal of Abeera BioAI is to make bioinformatics more accessible by providing an intelligent assistant that helps bridge the gap between biological concepts and computational tools.
"""

!pip install groq gradio

import os
os.environ["GROQ_API_KEY"] = "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"

{"role": "system", "content": "You are a bioinformatics expert helping students."}

from groq import Groq

client = Groq(api_key=os.environ.get("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"))

def chat_with_groq(message, history):
    messages = [{"role": "system", "content": "You are a helpful chatbot."}]

    # Add previous conversation (memory)
    for user_msg, bot_msg in history:
        messages.append({"role": "user", "content": user_msg})
        messages.append({"role": "assistant", "content": bot_msg})

    # Add current message
    messages.append({"role": "user", "content": message})

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=messages,
    )

    return response.choices[0].message.content

import gradio as gr

demo = gr.ChatInterface(
    fn=chat_with_groq,
 title="Abeera BioAI 🧬",
description="An AI-powered bioinformatics assistant for sequence analysis and computational biology."
)

demo.launch()